[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Lisbeth"
authors = [{name = "Graziella", email = "jochen.alt@gmx.net"}]
dynamic = ["version", "description"]